### ISSUE TITLE
onTeardown unsubscribes events that were never subscribed

### ISSUE THREAD

**Issue by RyanMilligan** [canjs/can-stache-bindings#428] opened 2018-02-06 21:51 UTC
In onTeardown(), unsubscribing the noop handler causes exceptions to be thrown because the translationHandler can not be found.

This also appears to be resulting in memory leaks from can-zone for some reason.

[Affected file](https://github.com/canjs/can-stache-bindings/blob/v3.11.10/can-stache-bindings.js#L1297-L1311)

**Comment by phillipskevin** [comment] 2018-02-06 22:27
@RyanMilligan can you remind me why this throws? I tried to reproduce it with this [sample code](https://gist.github.com/phillipskevin/b60894c9b607221c26b60e06d3974444) and it works ok.

**Comment by RyanMilligan** [comment] 2018-02-06 22:52
The exception is happening in [can-zone/lib/tasks.js](https://github.com/canjs/can-zone/blob/5028693a5a653a1ab8147eb686cb238cda2bbca5/lib/tasks.js#L244). When `handler` is undefined, it tries to dereference a property from it and throws the exception.

**Comment by phillipskevin** [comment] 2018-02-06 23:10
This is caused by https://github.com/canjs/can-zone/issues/161.

**Comment by phillipskevin** [comment] 2018-02-06 23:41
@RyanMilligan can you confirm this issue is resolved with https://github.com/canjs/can-zone/releases/tag/v0.6.18?

**Comment by chasenlehara** [comment] 2018-03-05 18:41
Closing this; @RyanMilligan please feel free to reopen if can-zone@0.6.18 doesn’t fix the issue for you.

**Closed as completed by chasenlehara** 2018-03-05 18:41 UTC
