### ISSUE TITLE
Passing Prop="value" sets lowercase "prop" on the ViewModel

### ISSUE THREAD

**Issue by green3g** [canjs/can-stache-bindings#397] opened 2018-01-18 15:19 UTC
When I pass a property to a component that is capitalized, it gets set on the component view model as the lowercase name of the property. 

```
<component-name Prop:from="other" />
```

gets set on the viewmodel as `prop`

https://jsbin.com/ligavawuma/edit?html,js,output

Why pass capitalized properties? Capitalized variables often represent constructors like a User model.

**Comment by phillipskevin** [comment] 2018-01-18 15:47
Thanks for reporting! This is caused by https://github.com/canjs/can-attribute-encoder/issues/15, so I'm going to close this one and we'll handle it there.

**Closed as completed by phillipskevin** 2018-01-18 15:47 UTC
